// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-5u2lr7Pa7rCp6-C0HXJXeN3e_CS2FQ8',
    appId: '1:301421926312:android:3a0d5f7e17521604e8ef9d',
    messagingSenderId: '301421926312',
    projectId: 'chat-app-16060',
    storageBucket: 'chat-app-16060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPLEgGuTo3Uy3og9ZnpfeuXPh3qSHDTm0',
    appId: '1:301421926312:ios:194c234ebb7ec665e8ef9d',
    messagingSenderId: '301421926312',
    projectId: 'chat-app-16060',
    storageBucket: 'chat-app-16060.appspot.com',
    iosClientId: '301421926312-v38hu1hjvpp7gj289h43jjufl7k9fthb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
